# Generated by Django 5.0.2 on 2024-02-20 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authorization_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="user_info",
            new_name="UserInfo",
        ),
    ]
