# Generated by Django 5.0.2 on 2024-02-22 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authorization_app", "0004_remove_userinfo_username_userinfo_password"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="UserInfo",
            new_name="RegisterUser",
        ),
    ]
